dist: trusty
language: node_js
node_js:
  - "10"
addons:
  ssh_known_hosts: steem-engine.com
deploy:
- provider: script
  skip_cleanup: true
  script: au build --env prod
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist $REMOTE_USER@$HOST:$REMOTE_APP_DIR
  on:
    branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_134e9820d8ee_key -iv $encrypted_134e9820d8ee_iv
  -in deploy-key.enc -out ./deploy-key -d
- eval "$(ssh-agent -s)"
- chmod 400 ./deploy-key
- ssh-add ./deploy-key
- ssh -i ./deploy-key $REMOTE_USER@$HOST pwd

install:
- yarn global add aurelia-cli
- yarn
